# Generated by Django 5.0.6 on 2026-07-23 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_payment_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='student_photos/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(blank=True, max_length=120)),
                ('payment_id', models.CharField(blank=True, max_length=200)),
                ('collection_id', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=40)),
                ('vendor', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='campaign.contribution')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='campaign.paymentinstallment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
