/** Données fictives pour tester le dashboard sans backend. */
export const DEMO_CONTRIBUTIONS = [
  {
    id: 101,
    contributor_type: 'etudiant',
    nom: 'Nkomo',
    prenom: 'Marie-Claire',
    display_name: 'Marie-Claire Nkomo',
    telephone: '+237677123456',
    email: 'marie.nkomo@student.ud.ac.cm',
    ecole: "Faculté de Médecine et des Sciences Pharmaceutiques de l'Université de Douala",
    niveau_academique: 'licence3',
    filiere: 'Médecine',
    mode_paiement: 'en_ligne',
    methode_preferee: 'orange',
    amount: 20000,
    payment_status: 'SUCCESSFUL',
    created_at: '2026-07-15T09:24:00Z',
  },
  {
    id: 102,
    contributor_type: 'etudiant',
    nom: 'Abanda',
    prenom: 'Jean-Paul',
    display_name: 'Jean-Paul Abanda',
    telephone: '+237694567890',
    email: 'jp.abanda@univ-yaounde1.cm',
    ecole: 'Faculté de Médecine et des Sciences Biomédicales de Yaoundé',
    niveau_academique: 'master1',
    filiere: 'Santé publique',
    mode_paiement: 'en_ligne',
    methode_preferee: 'mtn',
    amount: 20000,
    payment_status: 'SUCCESSFUL',
    created_at: '2026-07-15T14:10:00Z',
  },
  {
    id: 103,
    contributor_type: 'etudiant',
    nom: 'Manga',
    prenom: 'Stéphanie',
    display_name: 'Stéphanie Manga',
    telephone: '+237655334422',
    email: 's.manga@udschang.cm',
    ecole: "Faculté de Médecine et des Sciences Pharmaceutiques de l'Université de Dschang",
    niveau_academique: 'licence2',
    filiere: 'Pharmacie',
    mode_paiement: 'especes',
    methode_preferee: 'orange',
    amount: 20000,
    payment_status: 'PENDING',
    created_at: '2026-07-16T08:45:00Z',
  },
  {
    id: 104,
    contributor_type: 'etudiant',
    nom: 'Tchoumi',
    prenom: 'Eric',
    display_name: 'Eric Tchoumi',
    telephone: '+237678901234',
    email: 'eric.tchoumi@gmail.com',
    ecole: "Faculté de Médecine et des Sciences Biomédicales de l'Université de Garoua",
    niveau_academique: 'doctorat',
    filiere: 'Médecine',
    mode_paiement: 'en_ligne',
    methode_preferee: 'orange',
    amount: 20000,
    payment_status: 'SUCCESSFUL',
    created_at: '2026-07-16T11:30:00Z',
  },
  {
    id: 105,
    contributor_type: 'etudiant',
    nom: 'Fotsing',
    prenom: 'Brice',
    display_name: 'Brice Fotsing',
    telephone: '+237699887766',
    email: 'brice.f@montagnes.cm',
    ecole: 'Université des Montagnes',
    niveau_academique: 'licence1',
    filiere: 'Sciences infirmières',
    mode_paiement: 'especes',
    methode_preferee: 'mtn',
    amount: 20000,
    payment_status: 'PENDING',
    created_at: '2026-07-17T16:20:00Z',
  },
  {
    id: 106,
    contributor_type: 'etudiant',
    nom: 'Essomba',
    prenom: 'Patricia',
    display_name: 'Patricia Essomba',
    telephone: '+237671223344',
    email: 'p.essomba@issse.cm',
    ecole: 'École des Sciences de la Santé de Bertoua',
    niveau_academique: 'ide',
    filiere: 'IDE',
    mode_paiement: 'en_ligne',
    methode_preferee: 'mtn',
    amount: 20000,
    payment_status: 'FAILED',
    created_at: '2026-07-17T18:05:00Z',
  },
  {
    id: 107,
    contributor_type: 'etudiant',
    nom: 'Ndjock',
    prenom: 'Alain',
    display_name: 'Alain Ndjock',
    telephone: '+237656778899',
    email: 'alain.ndjock@doumaintang.cm',
    ecole: 'Institut des IDE de Doumaintang',
    niveau_academique: 'ide',
    filiere: 'Soins infirmiers',
    mode_paiement: 'en_ligne',
    methode_preferee: 'orange',
    amount: 20000,
    payment_status: 'SUCCESSFUL',
    created_at: '2026-07-18T07:15:00Z',
  },
  {
    id: 201,
    contributor_type: 'donateur',
    nom: 'Pharmacie du Centre',
    prenom: '',
    display_name: 'Pharmacie du Centre',
    telephone: '+237677445566',
    email: 'contact@pharmaciecentre.cm',
    ecole: '',
    mode_paiement: 'en_ligne',
    methode_preferee: 'orange',
    amount: 100000,
    payment_status: 'SUCCESSFUL',
    created_at: '2026-07-14T10:00:00Z',
  },
  {
    id: 202,
    contributor_type: 'donateur',
    nom: 'M. Nguefack',
    prenom: '',
    display_name: 'M. Nguefack',
    telephone: '+237694112233',
    email: '',
    ecole: '',
    mode_paiement: 'en_ligne',
    methode_preferee: 'mtn',
    amount: 25000,
    payment_status: 'SUCCESSFUL',
    created_at: '2026-07-15T19:30:00Z',
  },
  {
    id: 203,
    contributor_type: 'donateur',
    nom: 'Société BICEC Douala',
    prenom: '',
    display_name: 'Société BICEC Douala',
    telephone: '+237699001122',
    email: 'partenariat@bicec.cm',
    ecole: '',
    mode_paiement: 'en_ligne',
    methode_preferee: 'orange',
    amount: 500000,
    payment_status: 'SUCCESSFUL',
    created_at: '2026-07-16T09:00:00Z',
  },
  {
    id: 204,
    contributor_type: 'donateur',
    nom: 'Mme Atangana',
    prenom: '',
    display_name: 'Mme Atangana',
    telephone: '+237655667788',
    email: '',
    ecole: '',
    mode_paiement: 'en_ligne',
    methode_preferee: 'mtn',
    amount: 10000,
    payment_status: 'PENDING',
    created_at: '2026-07-18T12:40:00Z',
  },
  {
    id: 205,
    contributor_type: 'donateur',
    nom: 'Dr. Owona',
    prenom: '',
    display_name: 'Dr. Owona',
    telephone: '+237678334455',
    email: 'dr.owona@health.cm',
    ecole: '',
    mode_paiement: 'en_ligne',
    methode_preferee: 'orange',
    amount: 75000,
    payment_status: 'SUCCESSFUL',
    created_at: '2026-07-18T13:10:00Z',
  },
];

export const DEMO_GOAL = 5000000;
